### ISSUE TITLE
AllowImageRule - Panic when choosing "NO" for allowing apps to be deployed. 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1970]
**Acorn version** - `acorn version v0.8.0-alpha7-151-gc1b7f440+c1b7f440`

**Steps to reproduce the problem:**
1. Enable AllowImageRule -  `acorn install --features image-allow-rules=true`
2. Deploy app from Acornfile and choose "No" when prompted for allowing apps to be deployed. 

```
? Do you want to allow this app to use this (POTENTIALLY DANGEROUS) image? NO
mytestnew
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x394aefc]

goroutine 1 [running]:
github.com/acorn-io/runtime/pkg/cli.(*Run).Run.func2()
	github.com/acorn-io/runtime/pkg/cli/run.go:267 +0x17c
github.com/acorn-io/runtime/pkg/cli.(*Run).Run(0xc000999dc0, 0xc000748300, {0xc000a96330, 0x1, 0x3})
	github.com/acorn-io/runtime/pkg/cli/run.go:316 +0x73e
github.com/acorn-io/runtime/pkg/cli/builder.bind.func1(0xc000748300?, {0xc000a96330, 0x1, 0x3})
	github.com/acorn-io/runtime/pkg/cli/builder/builder.go:431 +0x214
github.com/spf13/cobra.(*Command).execute(0xc000748300, {0xc000a962d0, 0x3, 0x3})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005b00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/acorn-io/runtime/pkg/cli.RunAndHandleError({0x4860d38?, 0xc000290b40?}, 0xc000005b00?)
	github.com/acorn-io/runtime/pkg/cli/errors.go:17 +0x5d
main.main()
	github.com/acorn-io/runtime/main.go:15 +0x2f

```

**Comment by sangee2004** [comment]
Same error is also seen when deploying apps from an image.
```
acorn run -n mytestapp1 sangeetha/myfirstacorn:v0.0.1
  •  WARNING:  This application would like to use the image 'sangeetha/myfirstacorn:v0.0.1'.
                 This image is not trusted by any image allow rules in this project.
                 This could be VERY DANGEROUS to the cluster if you do not trust this
                 application. If you are unsure say no.

? Do you want to allow this app to use this (POTENTIALLY DANGEROUS) image? NO
mytestapp1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x394aefc]

goroutine 1 [running]:
github.com/acorn-io/runtime/pkg/cli.(*Run).Run.func2()
	github.com/acorn-io/runtime/pkg/cli/run.go:267 +0x17c
github.com/acorn-io/runtime/pkg/cli.(*Run).Run(0xc00053afc0, 0xc000dfe900, {0xc0005be330, 0x1, 0x3})
	github.com/acorn-io/runtime/pkg/cli/run.go:316 +0x73e
github.com/acorn-io/runtime/pkg/cli/builder.bind.func1(0xc000dfe900?, {0xc0005be330, 0x1, 0x3})
	github.com/acorn-io/runtime/pkg/cli/builder/builder.go:431 +0x214
github.com/spf13/cobra.(*Command).execute(0xc000dfe900, {0xc0005be2d0, 0x3, 0x3})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d76300)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/acorn-io/runtime/pkg/cli.RunAndHandleError({0x4860d38?, 0xc0002629b0?}, 0xc000d76300?)
	github.com/acorn-io/runtime/pkg/cli/errors.go:17 +0x5d
main.main()
	github.com/acorn-io/runtime/main.go:15 +0x2f
```

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.8.0-rc4+b6a95e8a`

There is no panic when choosing "No" for allowing apps to be deployed. Error message presented to user in this case is as expected.

```
? Do you want to allow this app to use this (POTENTIALLY DANGEROUS) image? NO
  ✗  ERROR:  image <5152028e4be8d70b36017721b64e22882a03818599e18c13f3e10f85ce313dfa> is not allowed by any ImageAllowRule in this project

% acorn run -n mytesthello <image>
  •  WARNING:  This application would like to use the image '<image-name>'.
                 This image is not trusted by any image allow rules in this project.
                 This could be VERY DANGEROUS to the cluster if you do not trust this
                 application. If you are unsure say no.

? Do you want to allow this app to use this (POTENTIALLY DANGEROUS) image? NO
  ✗  ERROR:  image <image-name> is not allowed by any ImageAllowRule in this project
```
