### ISSUE TITLE
Panic when deploying apps with images in autoupgrade format without registry.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1989]
acorn version v0.8.0-alpha7-172-gff1e20f9+ff1e20f9

```
 acorn run -n mytestnew sangeetha/myfirstacorn:v#.#.#
panic: interface conversion: error is *errors.StatusError, not *imageallowrules.ErrImageNotAllowed

goroutine 1 [running]:
github.com/acorn-io/runtime/pkg/cli.(*Run).Run(0xc00081d880, 0xc0003f6300, {0xc0008f0330, 0x1, 0x3})
	github.com/acorn-io/runtime/pkg/cli/run.go:289 +0xd06
github.com/acorn-io/runtime/pkg/cli/builder.bind.func1(0xc0003f6300?, {0xc0008f0330, 0x1, 0x3})
	github.com/acorn-io/runtime/pkg/cli/builder/builder.go:431 +0x214
github.com/spf13/cobra.(*Command).execute(0xc0003f6300, {0xc0008f02d0, 0x3, 0x3})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001af200)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/acorn-io/runtime/pkg/cli.RunAndHandleError({0x48611f8?, 0xc00013fa90?}, 0xc0001af200?)
	github.com/acorn-io/runtime/pkg/cli/errors.go:17 +0x5d
main.main()
	github.com/acorn-io/runtime/main.go:15 +0x2f

```

**Comment by iwilltry42** [comment]
Testing with 2bb41677, I get 
```
acorn run -n mytestnew 'sangeetha/myfirstacorn:v#.#.#'
  ✗  ERROR:  unable to find an image for sangeetha/myfirstacorn:v#.#.# matching pattern v#.#.# - if you are trying to use a remote image, specify the full registry
```
I assume that this was fixed along the way.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.8.0-rc4+b6a95e8a`

User is presented with following error message as expected with/without have image allow rules enabled.
```
acorn run -n mytestnew 'sangeetha/myfirstacorn:v#.#.#'
  ✗  ERROR:  unable to find an image for sangeetha/myfirstacorn:v#.#.# matching pattern v#.#.# - if you are trying to use a remote image, specify the full registry
```
